docs/advanced/accesstransformers.md

I've discovered that AT doc wasn't re-branded yet so here it is :)

Rebrand accesstransformers.md

---

docs/concepts/internationalization.md
docs/datagen/client/localization.md
docs/datagen/client/modelproviders.md
docs/datagen/index.md
docs/gameeffects/sounds.md
docs/misc/components.md
docs/misc/keymappings.md
docs/rendering/modelextensions/transforms.md
docs/resources/client/index.md
docs/resources/client/models/index.md
docs/resources/client/models/itemproperties.md
docs/resources/client/models/tinting.md
docs/resources/server/advancements.md
docs/resources/server/index.md
docs/resources/server/loottables.md
docs/resources/server/recipes/custom.md
docs/resources/server/recipes/index.md
docs/resources/server/recipes/ingredients.md
docs/resources/server/tags.md

The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: <https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom>. This PR updates all the URLs to the new domain: minecraft.wiki

Update Minecraft Wiki links to new domain after fork

---

docs/advanced/accesstransformers.mdx
neogradle/docs/configuration/index.mdx

This PR updates the docs for Access Transformers to reflect the changes in NeoGradle 7.0.41 ([link to PR](https://github.com/neoforged/NeoGradle/pull/41)) and FancyModLoader 2.0 ([link to PR](https://github.com/neoforged/FancyModLoader/pull/41)). All mentions to Access Transformers show the new format for specifying multiple AT files, as well as the requirement to specify non-default AT file locations in `mods.toml`.
Closes #36.
Preview URL: https://pr-38.neoforged-docs-previews.pages.dev

Added 20.2 updates to Access Transformer sections

---

docs/concepts/events.md
docs/concepts/lifecycle.md
docs/datastorage/attachments.md
docs/datastorage/capabilities.md
docs/datastorage/saveddata.md
docs/gui/menus.md
docs/resources/server/recipes/index.md

Mostly adapted from the blog post, but keeping some of the old content where that made sense.
Beyond the two main changed files, I also fixed references to capabilities elsewhere. Some of the other pages will still need an update, but at least everything related to caps should be clean now.
Preview URL: https://pr-34.neoforged-docs-previews.pages.dev

Update docs for capability rework

---

docs/networking/payload.md

This snippet referred to a class that doesn't exist.
I also fixed a typo in a variable name.
Preview URL: https://pr-43.neoforged-docs-previews.pages.dev

Fix example code in networking docs

---

docs/resources/server/advancements.md

A lot of the vanilla code for registering new Advancement criteria changed (I'm presuming in 1.20, but I hadn't much used it earlier). This includes both the names of classes and pretty large shifts from the currently documented requirements, such as no longer dealing directly with JSON objects. 
I believe this also should check one box of #20
Preview URL: https://pr-45.neoforged-docs-previews.pages.dev

Update documentation on custom Advancement criteria

---

docs/datamaps/_category_.json
docs/datamaps/index.md
docs/datamaps/neo_maps.md
docs/datamaps/structure.md
docusaurus.config.js

Depends on https://github.com/neoforged/NeoForge/pull/519 and a PR that makes compostables a data map.
Preview URL: https://pr-46.neoforged-docs-previews.pages.dev

Add a guide on the upcoming data maps

---

docs/datastorage/saveddata.md

Updates the `SavedData` docs to reflect vanilla's change in `1.20.2` to make `DimensionDataStorage#computeIfAbsent` take an instance of `SavedData.Factory`.
Also reworded some parts to make them clearer.
Preview URL: https://pr-47.neoforged-docs-previews.pages.dev

Update and reword SavedData

---

docusaurus.config.js
src/css/custom.css
src/pages/index.mdx
src/theme/Card.tsx

- Change the prism themes to make code blocks more highlighted (current theme used in dark mode codeblocks does more italic-fication than colouring)
- Improve the contrast of admonitions
- Change background colours to improve contrast.
- Remove text decorations for direct links to sections
- Separate h2 sections with a 1px solid border
- Make the carets a bit smaller (default is 50%/2em)
- Make the homepage cards scale in and out on hover
Preview URL: https://pr-53.neoforged-docs-previews.pages.dev

Update theming and colours

---

docs/advanced/accesstransformers.mdx

SRG Names are no longer needed, so I removed the warning about that and updated the examples.
Also moved the headers to the new standard.
Preview URL: https://pr-56.neoforged-docs-previews.pages.dev

Update Access Transformers docs

---

docs/concepts/internationalization.md
docs/gettingstarted/modfiles.md

Adds initial documentation for the new translatable mod info support [added in `v20.4.179`](https://github.com/neoforged/NeoForge/pull/649).
Preview URL: https://pr-57.neoforged-docs-previews.pages.dev

Document new mod info localization support

---

docs/rendering/modelloaders/index.md

The identity of the OBJ model loader inside the codebase has been changed from "forge:obj" into "neoforge:obj" but not yet for the documentation.
Discovered by chance when handling a weird model loading issue during my developing NeoForge mod.
Preview URL: https://pr-61.neoforged-docs-previews.pages.dev

Correct the model loader

---

docs/legacy/porting.md

This PR fixes the link "1.20.4 -> 1.20.5/6" in the porting page

Fix link in porting page

---

docs/gui/screens.md

Closes #26
Removes the extra `and` before textures.
Preview URL: https://pr-72.neoforged-docs-previews.pages.dev

Fix typing mistake in screen

---

docs/datastorage/codecs.md

`warn` is not a valid admonition, so it has been changed to `warning`.
Preview URL: https://pr-74.neoforged-docs-previews.pages.dev

Fix improper admonition

---

docs/datastorage/codecs.md

To construct a record codec after grouping, the `apply` method must be called supplying the instance, not as a second parameter of the `create` function. This properly constructs the example.

Fix recursive codec example

---

docs/gui/screens.md

Fixes how admonitions appear in the screen docs. Changes the closing admonition `:::caution` -> `:::`
Preview URL: https://pr-87.neoforged-docs-previews.pages.dev

Remove trailing `caution` at end of admonition in Screens

---

docs/concepts/events.md

Closes #88 
Updates the 'Result' section to talk about `TriState` and any `Result` enum implemented on the event class. Also provides some examples on how they are used.
Preview URL: https://pr-91.neoforged-docs-previews.pages.dev

Update TriState and Result enum Event Information

---

docs/gui/screens.md

`RenderSystem#setShaderTexture` is called internally by `blit`, so it can be removed from the docs.
Preview URL: https://pr-93.neoforged-docs-previews.pages.dev

Remove RenderSystem call in Screen docs

---

docs/advanced/accesstransformers.md
docs/gettingstarted/modfiles.md

Closes #98 
Adds a specification header and removes the tabs import as they no longer are used.
Preview URL: https://pr-101.neoforged-docs-previews.pages.dev

 Organize AT specification under a header

---

docs/misc/config.md

Closes #100 
Adds the `STARTUP` config type to list of available ones and updates the permalink to reflect the new docs in FML.
Might be worthwhile at some point to expand the config type section to include when its loaded, but that's for another time.
Preview URL: https://pr-102.neoforged-docs-previews.pages.dev

Add STARTUP to list of config types

---

docs/items/tools.md

Closes #113 
Registers the armor material within the example, which is supposed to be how its done, which fixes the subsequent example of using it as part of an `ArmorItem`.
Preview URL: https://pr-114.neoforged-docs-previews.pages.dev

Register Armor Materials in Example

---

docs/items/datacomponents.md

This PR updates the data component docs to use the specialized `DeferredRegister.DataComponents` and its registration helper instead of a plain `DeferredRegister` as it simplifies registration and avoids some generic inference issues with the builder.
Preview URL: https://pr-117.neoforged-docs-previews.pages.dev

Switch data component registration to specialized DeferredRegister

---

docs/items/tools.md
docs/resources/server/loottables.md

Closes #121 
Updates tool actions to item abilities. Additional documentation for `ItemAbilityPredicate` should be provided in #111.
Also, fixes a small bug where we are still mentioning the `forge` namespace in custom loot table additions.
Preview URL: https://pr-122.neoforged-docs-previews.pages.dev

Update ToolAction -> ItemAbility

---

docs/resources/client/particles.md

Closes #123 
Update the particle example to fix the NPE that occurs when the sprite isn't set in time for rendering.
Preview URL: https://pr-124.neoforged-docs-previews.pages.dev

Fix particle example to avoid NPE

---

docs/concepts/registries.md
docs/misc/gametest.mdx
docs/misc/resourcelocation.md
docs/resources/index.md
docs/resources/server/loottables.md
docs/resources/server/recipes/index.md

Depluralizes all registry and tag folders mentioned. Also fixes an example where `loot_modifiers` is not a datapack registry.
Preview URL: https://pr-126.neoforged-docs-previews.pages.dev

Depluralize Registry and Tag Folders

---

docs/gettingstarted/modfiles.md

Adds a basic description on the mixin config block in the neoforge.mods.toml file. Also fixes the links to the MDK.
Preview URL: https://pr-128.neoforged-docs-previews.pages.dev

Add Mixin Mods TOML Block and Fix MDK Links

---

docs/gettingstarted/versioning.md

Minor typo fix: bugs -> bug-fixes.

Fix small typo in Semantic Versioning section

---

docs/resources/server/datamaps/index.md

Updates the `DataMapProvider` example to use a holder instead of a registry object as the registry object cannot be passed in raw.
Preview URL: https://pr-144.neoforged-docs-previews.pages.dev

Update DataMapProvider example to take in holder

---

docs/resources/client/particles.md

Fixes the particle description info to say that it must be registered for certain provider methods. Also includes an addendum for how the particle description images are used.
Preview URL: https://pr-140.neoforged-docs-previews.pages.dev

Fix particle description information

---

docs/resources/server/datamaps/builtin.md

Also add the somewhat recently added `can_villager_compost` field to compostables.
Preview URL: https://pr-147.neoforged-docs-previews.pages.dev

Document the waxables and oxidizables data maps

---

docs/resources/server/datamaps/index.md

Adds a missing `.create` call on `RecordCodecBuilder` on the datamaps page.

Fixes small typo in datamaps docs

---

docs/items/mobeffects.md

Fixes a typo in the Mob Effects article that incorrectly references `Attribute` instead of `Attributes`.
Preview URL: https://pr-153.neoforged-docs-previews.pages.dev

Fix incorrect reference to `Attribute`

---

docs/resources/server/recipes/index.md

Fixes #154
- added missing creation of  the "recipes" variable
- fixes logic potentially causing client-server desync by only skipping server-only tasks instead of everything on the client
Preview URL: https://pr-155.neoforged-docs-previews.pages.dev

Fix "The Crafting Mechanic" example on "Recipes"

---

docs/advanced/_category_.json
docs/legacy/_category_.json
docs/misc/_category_.json
docs/networking/_category_.json
docs/worldgen/_category_.json
docs/worldgen/biomemodifier.md

This is based off of the work from both ChampionAsh and the Gemwire wiki:
https://github.com/ChampionAsh5357/NeoForge-Docs/blob/feat/worldgen-primer/docs/worldgen/biomes/biomemodifiers.md
https://forge.gemwire.uk/wiki/Biome_Modifiers
My goal here was to take an approach to try and keep the docs more simple for readers and push the more technical stuff into the data generation/custom biome modifier sections. The reason for this is this document is going to be linked to both pack makers and beginner modders who may not be datagenning.
To help ease into the docs, it starts off with a brief overview of what Biome Modifiers are and can do. And then it lists which section to check out for if the reader is a player/pack maker, a modder with basic needs, or an advanced modder that needs something …

Biome Modifier documentation

---

docs/worldgen/biomemodifier.md

Seems it has to be lowercase for it to work online even though uppercase worked locally
Preview URL: https://pr-167.neoforged-docs-previews.pages.dev

Fix anchors in Biome Modifier docs

---

docs/resources/server/advancements.md

This PR fix two things in the [advancements](https://docs.neoforged.net/docs/resources/server/advancements/) page.
In the docs, there is written that for the [`performExampleAction`](https://docs.neoforged.net/docs/resources/server/advancements/#calling-criterion-triggers), we need to use get our registry but with the  non-existent `value()` method  and it should be replaced with the `get()` method.
This is a minor change. To datagen an advancement, we need to create a class that implements `AdvancementProvider.AdvancementGenerator`. This interface have the `generate` method with theses paramaters `HolderLookup.Provider registries`, `Consumer<AdvancementHolder> saver`, `ExistingFileHelper existingFileHelper` but in the docs, the parameter `consumer` is named `saver`
In the docs, to add a …

Fix Advancements page

---

docs/blockentities/index.md

Closes #175 
Calls `Supplier#get` when trying to resolve the `BlockEntityType` as it mentions using referenced `DeferredBlock`s.
Preview URL: https://pr-176.neoforged-docs-previews.pages.dev

Resolve blocks passed to block entity

---

docs/resources/server/damagetypes.md

Fixes wrong death message id in DamageTypes docs

---

docs/resources/server/loottables/custom.md
versioned_docs/version-1.21.1/resources/server/loottables/custom.md

Closes #195 
Adds the generic wildcard and function for the `LootItemFunctionType` registry examples
Preview URL: https://pr-205.neoforged-docs-previews.pages.dev

Add generic type for loot function example

---

docs/resources/client/models/datagen.md
versioned_docs/version-1.20.4/resources/client/models/datagen.md
versioned_docs/version-1.20.6/resources/client/models/datagen.md
versioned_docs/version-1.21.1/resources/client/models/datagen.md

Closes #187 
Properly handles all calls to `withExistingParent` by supplying the correct parameters. Also fixes how to add a multipart block state.
Preview URL: https://pr-206.neoforged-docs-previews.pages.dev

Fix example calls to withExistingParent

---

versioned_docs/version-1.21.1/resources/server/recipes/index.md

`group` is marked final, but is not a constructor parameter. since it's optional, it shouldnt be final
Preview URL: https://pr-210.neoforged-docs-previews.pages.dev

server recipes: make group non-final

---

docs/networking/streamcodecs.md

The class is correctly capitalized `ByteBufCodecs` everywhere else, but in this one example the `Buf` has become `buf`.

Fix miscapitalized `ByteBufCodecs` in streamcodecs.md

---

.github/workflows/build-pr.yml

v3 of some of the Github Actions have been disabled since January 30th, 2025. This updates the actions to their v4 counterparts, allowing PR building and preview deployment to function.
Preview URL: https://pr-224.neoforged-docs-previews.pages.dev

Update Github actions to v4

---

docs/advanced/featureflags.md
docs/concepts/registries.md
docs/items/armor.md
docs/resources/client/i18n.md
docs/resources/client/models/datagen.md
docs/resources/client/particles.md
docs/resources/client/sounds.md
docs/resources/index.md
docs/resources/server/advancements.md
docs/resources/server/damagetypes.md
docs/resources/server/datamaps/index.md
docs/resources/server/enchantments/index.md
docs/resources/server/loottables/glm.md
docs/resources/server/loottables/index.md
docs/resources/server/recipes/index.md
docs/resources/server/tags.md
docs/worldgen/biomemodifier.md

Updates the usage of the `GatherDataEvent` to its current implementation in 1.21.4. Also switches all examples to use one of the available `create*` methods as required.
Preview URL: https://pr-223.neoforged-docs-previews.pages.dev

[1.21.4] Update usage of `GatherDataEvent` and the `create*` methods

---

docs/resources/client/models/items.md

Closes #229 
Readds the fluid container model docs that were removed in 1.21.3.
Preview URL: https://pr-232.neoforged-docs-previews.pages.dev

Add fluid container model docs

---

docs/gettingstarted/modfiles.md
docusaurus.config.js
versioned_docs/version-1.20.4/gettingstarted/modfiles.md
versioned_docs/version-1.20.6/gettingstarted/modfiles.md
versioned_docs/version-1.21.1/gettingstarted/modfiles.md
versioned_docs/version-1.21.3/gettingstarted/modfiles.md

At the moment, only the [Parchment site](https://docs.neoforged.net/neogradle/docs/parchment) uses a `properties` area, but maybe there will be more in the future.
Before: https://docs.neoforged.net/neogradle/docs/parchment
After: https://pr-233.neoforged-docs-previews.pages.dev/neogradle/docs/parchment
Preview URL: https://pr-233.neoforged-docs-previews.pages.dev

Add support for syntax highlighting of '.properties' files

---

docs/datastorage/attachments.md

Fixes a missed change where the `AttachmentType` on serialize in the builder takes in a `MapCodec` instead of a `Codec`.
Preview URL: https://pr-257.neoforged-docs-previews.pages.dev

[1.21.6+] Fix attachment to take in map codec instead of codec

---

docs/gui/menus.md

Closes #242 
Reorganizes the data synchronization subsection in menus to specifically show how to add a data slot, container data, and slots. Also adds more information regarding slots and removing the general deprecation of container.
Preview URL: https://pr-278.neoforged-docs-previews.pages.dev

Clarify Data Synchronization in Menus

---

docs/gui/menus.md
versioned_docs/version-1.20.6/gui/menus.md
versioned_docs/version-1.21.1/gui/menus.md
versioned_docs/version-1.21.3/gui/menus.md
versioned_docs/version-1.21.4/gui/menus.md
versioned_docs/version-1.21.5/gui/menus.md

https://mappings.dev/1.21.1/net/minecraft/world/level/block/state/BlockBehaviour.html
Method `useWithoutItem` does not take `InteractionHand`.
Preview URL: https://pr-280.neoforged-docs-previews.pages.dev

Fix block implementation example

---

.github/workflows/build-pr.yml
.github/workflows/version-update.yml

Switches to using `npm ci` within Github runners.
Preview URL: https://pr-282.neoforged-docs-previews.pages.dev

Use npm ci in CI/CD

---

versioned_docs/version-1.21.1/resources/server/datamaps/builtin.md
versioned_docs/version-1.21.3/resources/server/datamaps/builtin.md
versioned_docs/version-1.21.4/resources/server/datamaps/builtin.md
versioned_docs/version-1.21.5/resources/server/datamaps/builtin.md

In 1.21.1, the correct key for entries in the oxidizables data map is `next_oxidation_stage`, not `next_oxidized_stage` (source: https://github.com/neoforged/NeoForge/blob/1.21.x/src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/Oxidizable.java#L24C68-L24C88)
Preview URL: https://pr-283.neoforged-docs-previews.pages.dev

Correct the keys stated to be used in the oxidized data map
