docs/blockentities/ber.md, docs/blocks/index.md, docs/concepts/lifecycle.md, docs/concepts/registries.md, docs/datastorage/capabilities.md, docs/gettingstarted/index.md, docs/gettingstarted/modfiles.md, docs/gui/screens.md, docs/items/index.md, docs/resources/server/advancements.md, docs/resources/server/glm.md, docs/resources/server/loottables.md
The 1.20 changes were overwritten by me when messing around with versioning while porting to Docusaurus. This PR adds them back.
Preview URL: https://pr-6.neoforged-docs-previews.pages.dev
=> Add 1.20 changes

docs/misc/components.md
😅 I made a huge mistake when writing this, confused between internalization and internationalization
Preview URL: https://pr-17.neoforged-docs-previews.pages.dev
=> Fix markdown link in components.md

docusaurus.config.js, package-lock.json, package.json
All is in the title ^^.
Should be merged before #9 to test if changes for this PR is OK with Docusaurus V3.
Preview URL: https://pr-25.neoforged-docs-previews.pages.dev
=> Upgrade to Docusaurus v3

docs/datamaps/neo_maps.md
Documents the new data maps for furnace fuels, vibration frequencies and parrot imitation.
Preview URL: https://pr-50.neoforged-docs-previews.pages.dev
=> Document the new data maps

docs/datamaps/neo_maps.md, docs/gui/screens.md
Preview URL: https://pr-51.neoforged-docs-previews.pages.dev
=> Update menu screens guide regarding `RegisterMenuScreensEvent`

docs/resources/server/conditional.md
Update the conditions page to the new keys and the neo mod id and add an example.
Preview URL: https://pr-55.neoforged-docs-previews.pages.dev
=> Update the conditions page

docs/datamaps/neo_maps.md
See neoforged/neoforge#918.
Preview URL: https://pr-66.neoforged-docs-previews.pages.dev
=> Add documentation for monster room datamap

docs/datastorage/attachments.md, docs/datastorage/nbt.md, docs/items/datacomponents.md, docs/items/index.md, docs/items/tools.md, docs/resources/server/recipes/ingredients.md
Adds documentation for data components and updates the associated links on other pages.
Preview URL: https://pr-75.neoforged-docs-previews.pages.dev
=> Tags? No! It's Data Components!

docs/gettingstarted/modfiles.md
Provides more detailed information about the mod constructor in addition to what arguments are accepted.
Preview URL: https://pr-76.neoforged-docs-previews.pages.dev
=> Provide More Information about Mod Constructor

docs/resources/client/i18n.md
Readds information about mutable components as operations for adding siblings and styles are only available on `MutableComponent`s.
Preview URL: https://pr-77.neoforged-docs-previews.pages.dev
=> Add information about MutableComponent

docs/advanced/extensibleenums.md
Adds documentation for extensible enums along with how to add extensible enums to NeoForge.
This will likely need to be updated depending on the state of neoforged/NeoForge#970.
Preview URL: https://pr-78.neoforged-docs-previews.pages.dev
=> Extensible Enums, brought to you by Magic(TM)

docs/concepts/registries.md, versioned_docs/version-1.20.4/concepts/registries.md
IModEventBus isn't a thing!
Preview URL: https://pr-81.neoforged-docs-previews.pages.dev
=> Fix IEventBus in mod constructor

docs/gui/screens.md
Hrm... I put it in my branch name, but should make it clearer: this is just for the paragraph, and it's following sentence, headed "Relative Coordinates" in `screens.md`.
Preview URL: https://pr-89.neoforged-docs-previews.pages.dev
=> Small grammar, flow, and clarity edits

docs/networking/payload.md
Closes #104 
Just a field rename.
Preview URL: https://pr-105.neoforged-docs-previews.pages.dev
=> Type -> TYPE Text Fix

docs/misc/keymappings.md
Closes #115 
Replaces phases in `ClientTickEvent` with `ClientTickEvent.Post`.
Preview URL: https://pr-116.neoforged-docs-previews.pages.dev
=> Fix ClientTickEvent phases no longer existing

docs/networking/payload.md, versioned_docs/version-1.20.6/networking/index.md, versioned_docs/version-1.20.6/networking/payload.md
Closes #118 
Fixes a typo within the event and adds information on sending packets for the 1.20.6+ docs.
Preview URL: https://pr-119.neoforged-docs-previews.pages.dev
=> Readd Information about PacketDistributor

docs/gettingstarted/index.md, versioned_docs/version-1.20.4/gettingstarted/index.md, versioned_docs/version-1.20.6/gettingstarted/index.md
Updates the MDK links in the getting started page. The instructions have not changed.
Preview URL: https://pr-134.neoforged-docs-previews.pages.dev
=> Update MDK links

docs/misc/config.md
The released PR: https://github.com/neoforged/NeoForge/pull/1199
Preview URL: https://pr-137.neoforged-docs-previews.pages.dev
=> Add configuration screen documentation

docs/gui/menus.md
Fixes the menu constructor example by specifying where additional parameters should be added.
Preview URL: https://pr-139.neoforged-docs-previews.pages.dev
=> Fix menu constructor example

docs/resources/server/recipes/index.md
Update incorrect `recipes` -> `recipe`.
Preview URL: https://pr-151.neoforged-docs-previews.pages.dev
=> Update recipes -> recipe

docs/networking/payload.md
Closes #149 
Updates the docs to mention that running packets on the main thread is done by default. In addition, add some more information about running the payload on the network thread.
Preview URL: https://pr-156.neoforged-docs-previews.pages.dev
=> Fix Network Changes on Payload Thread Handling

docs/datastorage/attachments.md, docs/datastorage/nbt.md, docs/items/datacomponents.mdx, docs/items/index.md, docs/items/tools.md, docs/resources/server/datamaps/builtin.md, docs/resources/server/loottables/lootfunctions.md
Closes #162 
Adds a tab for post 21.1.48 on registering data components using the new method.
Preview URL: https://pr-164.neoforged-docs-previews.pages.dev
=> Update data components registrar method

docs/advanced/featureflags.md
Simply changes the default file location for feature flags
=> Change feature flags default file location

docs/worldgen/biomemodifier.md
Was suggested in here to mention how to handle Pale Garden biome
https://github.com/neoforged/NeoForge/issues/1649#issuecomment-2452598540
Preview URL: https://pr-189.neoforged-docs-previews.pages.dev
=> Mention how to target unregistered biomes

versioned_docs/version-1.21.1/resources/server/recipes/index.md
=> fix type for RecipeSerializer doc

docusaurus.config.js
Undoes parts of https://github.com/neoforged/Documentation/commit/f4f403a87c5e02ffaa46a850be0f3dfe6310f474#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2aR174
Preview URL: https://pr-220.neoforged-docs-previews.pages.dev
=> Fix copyright year

docs/resources/server/datamaps/builtin.md, versioned_docs/version-1.21.1/resources/server/datamaps/builtin.md, versioned_docs/version-1.21.3/resources/server/datamaps/builtin.md
Preview URL: https://pr-226.neoforged-docs-previews.pages.dev
=> Add neoforge:villager_types Datamap to BuiltIn Maps

docs/worldgen/biomemodifier.md, versioned_docs/version-1.21.1/worldgen/biomemodifier.md, versioned_docs/version-1.21.3/worldgen/biomemodifier.md
Closes https://github.com/neoforged/Documentation/issues/227
In the current version of the documentation, this code...
```java
public static final Holder<MapCodec<? extends BiomeModifier>> EXAMPLE_BIOME_MODIFIER =
BIOME_MODIFIERS.register("example_biome_modifier", () -> RecordCodecBuilder.mapCodec(instance ->
instance.group(
Biome.LIST_CODEC.fieldOf("biomes").forGetter(ExampleBiomeModifier::biomes),
Codec.INT.fieldOf("value").forGetter(ExampleBiomeModifier::value)
).apply(instance, ExampleBiomeModifier::new)
));
```
...throws this error.
```
Required type                                                  Provided
t1: App<Mu<BiomeModifier>, T1>                     RecordCodecBuilder<ExampleBiomeModifier,HolderSet<Biome>>
t2: App<Mu<BiomeModifier>, T2> …
```
=> Fixed incorrect BiomeModifier example code

docs/datastorage/saveddata.md, versioned_docs/version-1.20.4/datastorage/saveddata.md, versioned_docs/version-1.20.6/datastorage/saveddata.md, versioned_docs/version-1.21.1/datastorage/saveddata.md, versioned_docs/version-1.21.3/datastorage/saveddata.md
Just a small PR to add static to some of the methods in the example.
Preview URL: https://pr-230.neoforged-docs-previews.pages.dev
=> Added statics to the example of Saved Data

docs/networking/payload.md, docs/resources/client/models/items.md, docusaurus.config.js
Updates the docs to 1.21.7. This is a merge with the current docs as 21.6 will remain in beta.
Preview URL: https://pr-256.neoforged-docs-previews.pages.dev
=> Update to 1.21.7

docs/gui/screens.md, versioned_docs/version-1.20.4/gui/screens.md, versioned_docs/version-1.20.6/gui/screens.md, versioned_docs/version-1.21.1/gui/screens.md, versioned_docs/version-1.21.3/gui/screens.md, versioned_docs/version-1.21.4/gui/screens.md, versioned_docs/version-1.21.5/gui/screens.md
Preview URL: https://pr-267.neoforged-docs-previews.pages.dev
=> miscopy fix

scripts/initialize.js
Adds the neo news release as an embedded iframe into the docs.
Preview URL: https://pr-281.neoforged-docs-previews.pages.dev
=> Add Neo Releases as Primer Embeds
